@startuml
!include .\\App.xaml.puml
!include .\\AssemblyInfo.puml
!include .\\MainWindow.xaml.puml
!include .\\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows\App.g.puml
!include .\\obj\Debug\net8.0-windows\MainWindow.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_11sf4qfl_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_11sf4qfl_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_1irsaowy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_1irsaowy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_btouxtbo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_btouxtbo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_eo4rcyaq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_eo4rcyaq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hkkxmbjz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hkkxmbjz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hpvg0j4d_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hpvg0j4d_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hrxmd4lo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_hrxmd4lo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_mhc02nlz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_mhc02nlz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_ncpr5efj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_ncpr5efj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_qhvgaarr_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_qhvgaarr_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_retyaovu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_retyaovu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_u1nmu4zi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_u1nmu4zi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_y314ixgr_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_y314ixgr_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_y5vamja4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_y5vamja4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_ycm24c0k_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\OmvandTextApp_ycm24c0k_wpftmp.GlobalUsings.g.puml
@enduml
